trigger:
 branches:
   include:
     - main/core

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
  
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'b5f11e6f-5f5f-4e7f-858d-ec234c2e8e65/f2b5a7a4-ac8f-4f88-a080-41ad3831c4ee'
    allowPackageConflicts: true