name: core-nightly-package

env:
  OUTDIR: ./output
  CONFIG: Release
  RELEASE: 'beta001'

on: [workflow_dispatch]
# schedule:
# - cron: "0 0 * * *"

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: core/main

    - name: Get Date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d')"
      shell: bash

    - name: Set Release Suffix
      run: echo "SUFFIX=$SUFFIX" >> $GITHUB_ENV
      shell: bash
      env:
        SUFFIX: ${{env.RELEASE}}.${{steps.date.outputs.date}}.${{github.run_number}}

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: '%NUGET_AUTH_TOKEN%'

    - name: Restore dependencies
      run: dotnet restore --noLogo
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Package Core
      run: dotnet pack \uSync.Core\uSync.Core.csproj -c ${{env.CONFIG}} -o ${{env.OUTDIR}} --version-suffix ${{env.SUFFIX}} /p:ContinuousIntegrationBuild=true --no-restore

    - name: Package BackOffice
      run: dotnet pack \uSync.BackOffice\uSync.BackOffice.csproj -c ${{env.CONFIG}} -o ${{env.OUTDIR}} --version-suffix ${{env.SUFFIX}} /p:ContinuousIntegrationBuild=true --no-restore

    - name: publish to git
      run: dotnet nuget push ${{env.OUTDIR}}/*.nupkg --skip-duplicate
      env:
        NUGET_AUTH_TOKEN: ${{ github.token }}