name: core-nightly-package

env:
  OUTDIR: .\output
  CONFIG: Release
  RELEASE: 'beta002'
  DOTNET_NOLOGO: true

on: [workflow_dispatch]
# schedule:
# - cron: "0 0 * * *"

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: core/main

    - name: Set Release Suffix
      run: echo "SUFFIX=$SUFFIX" >> $GITHUB_ENV
      shell: bash
      env:
        SUFFIX: ${{env.RELEASE}}.${{github.run_number}}

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore --noLogo
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Package Core
      run: dotnet pack .\uSync.Core\uSync.Core.csproj -c ${{env.CONFIG}} -o ${{env.OUTDIR}} --version-suffix ${{env.SUFFIX}} /p:ContinuousIntegrationBuild=true --no-restore

    - name: Package BackOffice
      run: dotnet pack .\uSync.BackOffice\uSync.BackOffice.csproj -c ${{env.CONFIG}} -o ${{env.OUTDIR}} --version-suffix ${{env.SUFFIX}} /p:ContinuousIntegrationBuild=true --no-restore

    - name: publish packages to nightly feed
      run: dotnet nuget push ${{env.OUTDIR}}\*.nupkg --skip-duplicate -k $NUGET_AUTH_TOKEN -s https://pkgs.dev.azure.com/jumoo/Public/_packaging/nightly/nuget/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_KEY}}

